main/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from cities.views import CityView
from leds.views import JsonContent

urlpatterns = [
                  url(r'^admin/', include(admin.site.urls)),

                  url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
                  url(r'^cities$', TemplateView.as_view(template_name='cities.html'), name='cities'),

                  url(r'^cities/(?P<slug>.*)$', CityView.as_view(), name='city'),
                  url(r'^about/', TemplateView.as_view(template_name='about.html'), name='about_led'),
                  url(r'^contacts/', TemplateView.as_view(template_name='contacts.html'), name='contacts'),
                  url(r'^api/', csrf_exempt(JsonContent.as_view()), name='api'),

                  url(r'^redactor/', include('redactor.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leds/models.py
#! coding: UTF-8
from django.db import models
from django_ymap.fields import YmapCoord
from redactor.fields import RedactorField


class Led(models.Model):
    name = models.CharField(max_length=255, verbose_name=u'Название')
    city = models.ForeignKey('cities.City', verbose_name=u'Город')
    address = models.CharField(max_length=255, verbose_name=u'Адрес')
    text = RedactorField(blank=True, verbose_name=u'Описание')

    center = YmapCoord(max_length=200, default=None, blank=True, null=True, start_query=u'Москва', size_width=980,
                       size_height=500, verbose_name=u'Центр')


    class Meta:
        verbose_name = u'Экран'
        verbose_name_plural = u'Экраны'

    def __unicode__(self):
        return self.name

class LedImage(models.Model):
    led = models.ForeignKey('Led')
    image = models.ImageField(upload_to='uploads', verbose_name=u'Фотография')

    class Meta:
        verbose_name = u'Фотография экрана'
        verbose_name_plural = u'Фотографии'

    def __unicode__(self):
        return u''


class LedGroup(models.Model):
    name = models.CharField(max_length=255, verbose_name=u'Название')
    leds = models.ManyToManyField('Led', verbose_name=u'Связанные экраны')
    city = models.ForeignKey('cities.City', verbose_name=u'Город')

    def led_array(self):
        return list(self.leds.values_list('id', flat=True))

    class Meta:
        verbose_name = u'Пакет'
        verbose_name_plural = u'Пакеты экранов'

    def __unicode__(self):
        return self.name

main/models.py
#! coding: UTF-8
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import permalink
from django_ymap.fields import YmapCoord
from redactor.fields import RedactorField


class Order(models.Model):
    company = models.CharField(max_length=255, verbose_name=u'Компания')
    person = models.CharField(max_length=255, verbose_name=u'Контактное лицо')
    email = models.EmailField(max_length=255, verbose_name=u'Email')
    phone = models.CharField(max_length=255, verbose_name=u'Телефон')
    comment = models.TextField()

    leds = models.ManyToManyField('leds.Led', verbose_name=u'Экраны в заказе')
    groups = models.ManyToManyField('leds.LedGroup', verbose_name=u'Пакеты в заказе')

    success = models.BooleanField(default=False, verbose_name=u'Выполнен')

    class Meta:
        verbose_name = u'Заказ'
        verbose_name_plural = u'Заказы'

    def get_admin_link(self):
        return reverse('admin:main_order_change', args=(self.id,))

    def __unicode__(self):
        return '%s, %s' %(self.pk, self.person)


class Question(models.Model):
    name = models.CharField(max_length=255, verbose_name=u'Имя')
    phone = models.CharField(max_length=255, verbose_name=u'Телефон')
    email = models.EmailField(max_length=255, verbose_name=u'Email')
    issue = models.TextField(verbose_name=u'Вопрос')
    success = models.BooleanField(default=False, verbose_name=u'Решен')

    class Meta:
        verbose_name = u'Вопрос'
        verbose_name_plural = u'Вопросы'

    def __unicode__(self):
        return '%s, %s' %(self.name, self.issue)

    def get_admin_link(self):
        return reverse('admin:main_question_change', args=(self.id,))


class FastBid(models.Model):
    text = models.TextField(verbose_name=u'Быстрая заявка')
    success = models.BooleanField(default=False, verbose_name=u'Обработана')

    class Meta:
        verbose_name = u'Быструю заявку'
        verbose_name_plural = u'Быстрые заявки'

    def __unicode__(self):
        return self.text

    def get_admin_link(self):
        return reverse('admin:main_fastbid_change', args=(self.id,))

class LedoutdoorSettings(models.Model):
    index = RedactorField(verbose_name=u'Соержимое главной страницы', blank=True)
    about_led = RedactorField(verbose_name=u'Содержимое страницы "О LED экранах"', blank=True)
    contacts = RedactorField(verbose_name=u'Содержимое страницы "Контакты"', help_text=u'Содержание верхнего блока на странице "Контакты"', blank=True)
    phone_n = models.CharField(max_length=255, verbose_name=u'Телефон', help_text=u'Отображается в верхнем углу сайта на главной странице', blank=True)
    email_n = models.CharField(max_length=255, verbose_name=u'Почта', help_text=u'Отображается в верхнем углу сайта на главной странице', blank=True)
    email_for_notice = models.CharField(max_length=255, verbose_name=u'Почта для связи', help_text=u'На эту почту будут отсылаться уведомление о заказах', blank=True)
    address_coord = YmapCoord(max_length=200, default=None, blank=True, null=True, start_query=u'Москва', size_width=980,
                       size_height=500, verbose_name=u'Адрес офиса')

    title_index = models.CharField(max_length=255, verbose_name=u'Заголовок главной страницы', blank=True)
    description_index = models.CharField(max_length=255, verbose_name=u'Описание главной страницы', blank=True)
    keywords_index = models.CharField(max_length=255, verbose_name=u'Ключевые слова главной страницы', blank=True)

    title_cities = models.CharField(max_length=255, verbose_name=u'Заголовок страницы каталога', blank=True)
    description_cities = models.CharField(max_length=255, verbose_name=u'Описание страницы каталога', blank=True)
    keywords_cities = models.CharField(max_length=255, verbose_name=u'Ключевые слова страницы каталога', blank=True)

    title_about_led = models.CharField(max_length=255, verbose_name=u'Заголовок страницы о LED экранах', blank=True)
    description_about_led = models.CharField(max_length=255, verbose_name=u'Описание страницы о LED экранах', blank=True)
    keywords_about_led = models.CharField(max_length=255, verbose_name=u'Ключевые слова страницы о LED экранах', blank=True)

    title_city = models.CharField(max_length=255, verbose_name=u'Заголовок страницы города', blank=True, help_text=u'''
    Эти поля принимают шаблон, доступные переменные {{slug}}, {{description}}, {{name}}, {{center}}''')
    description_city = models.CharField(max_length=255, verbose_name=u'Описание страницы города', blank=True)
    keywords_city = models.CharField(max_length=255, verbose_name=u'Ключевые слова страницы города', blank=True)

    title_contact = models.CharField(max_length=255, verbose_name=u'Заголовок страницы контактов', blank=True)
    description_contact = models.CharField(max_length=255, verbose_name=u'Описание страницы контактов', blank=True)
    keywords_contact = models.CharField(max_length=255, verbose_name=u'Ключевые слова страницы контактов', blank=True)

    footer = RedactorField(verbose_name=u'Подвал', help_text=u'Отображается оостветственно в подвале сайта')
    snippets = models.TextField(blank=True, verbose_name=u'Код', help_text=u'JS код для счетчиков и прочего, вставляется в конец сайта')

    advantages_1 = models.TextField(blank=True)
    advantages_2 = models.TextField(blank=True)
    advantages_3 = models.TextField(blank=True)

    class Meta:
        verbose_name = u'Настройки сайта'
        verbose_name_plural = u'Настройки сайта'

    def __unicode__(self):
        return u'Настройки'

main/templates/dialogs/details.html
{% load thumbnail %}
<div class="ngdialog-header">
    <a href="javascript:void(0)" class="pseudo-link" ng-click="closeThisDialog()">Закрыть</a>

    <span ng-switch="$root.leds[{{ led.id }}]">
        <a href="javascript:void(0)" ng-click="$root.leds[{{ led.id }}] = false" ng-switch-when="true" class="btn">Убрать
            из заказа</a>
        <a href="javascript:void(0)" ng-click="$root.leds[{{ led.id }}] = true" ng-switch-default class="btn">Добавить в
            заказ</a>
    </span>

    <p class="title">{{ led.name }}, {{ led.address }}</p>
</div>
<div class="ngdialog-led-details">
    <div class="view-checker">
        {% for photo in led.ledimage_set.all %}
            <a ng-click="activeTab = 'photo_{{ forloop.counter }}'"{% if forloop.first %}
               ng-init="activeTab = 'photo_{{ forloop.counter }}'"{% endif %}
               ng-class="{'btn--disabled': activeTab != 'photo_{{ forloop.counter }}'}"
               class="btn">ФОТО {{ forloop.counter }}</a>
        {% empty %}
            {% if led.text %}
                <a ng-click="activeTab = 'info'" ng-class="{'btn--disabled': activeTab != 'info'}"
                   ng-init="activeTab = 'info'" class="btn">ИНФО</a>
            {% else %}
                <span ng-init="activeTab = 'map'"></span>
            {% endif %}
        {% endfor %}
        <a ng-click="activeTab = 'map'" ng-class="{'btn--disabled': activeTab != 'map'}" class="btn">КАРТА</a>
    </div>
    <div class="ngdialog-led-map" ng-show="activeTab == 'map'">
        <ya-map ya-zoom="16" ya-center="'{{ led.center }}'.split(',').reverse()">
            <ya-geo-object
                    ya-source="{geometry: {type: 'Point', coordinates: '{{ led.center }}'.split(',').reverse()}}"
                    ya-options="{preset: 'islands#dotIcon', iconColor: '#0496b0'}"></ya-geo-object>
        </ya-map>
    </div>
    {% for photo in led.ledimage_set.all %}
        <div class="ngdialog-led-photo" ng-show="activeTab == 'photo_{{ forloop.counter }}'">
            {% thumbnail photo.image '642' crop='center' as im %}
                <img src="{{ im.url }}" alt="Фотография_{{ led.name }}">
            {% endthumbnail %}
        </div>
    {% endfor %}
    {% if led.text %}
        <div class="ngdialog-led-info{% if not led.ledimage_set.count %} mt-20{% endif %}"
             ng-show="activeTab != 'map'">
            {{ led.text|safe }}
        </div>
    {% endif %}
</div>

main/templates/dialogs/fastbid.html
{% load thumbnail %}
<div class="ngdialog-header">
    <a href="javascript:void(0)" class="btn" ng-click="closeThisDialog()">Закрыть</a>

    <p class="title">Быстрая заявка</p>

</div>


<div ng-show="bidSended" class="thanks-info title">
    Спасибо за заявку, скоро мы свяжемся с вами
</div>

<div class="ngdialog-order-form">
    <div ng-hide="bidSended">
        <form name="fastForm">
    <textarea name="bid" ng-class="{error: fastForm.bid.$error.required}" ng-model="customer.bid"
              class="control" required
              placeholder="Отправьте нам запрос в произвольной форме, и мы свяжемся с вами, незабудьте указать контактные данные"></textarea>

            <div class="text-center mt-20">
                <a href="javascript:void(0)" ng-click="sendBid()" class="btn btn--big"
                   ng-class="{'btn--disabled': !fastForm.$valid}">отправить</a>
            </div>
        </form>
    </div>
</div>

main/templates/dialogs/order.html
{% load thumbnail %}
<div class="ngdialog-header">
    <a href="javascript:void(0)" class="btn" ng-click="closeThisDialog()">Закрыть</a>

    <p class="title" ng-show="$root.in_order_count() > 0">Оформление заявки на расчет рекламной кампании</p>

    <div class="title__small" ng-show="$root.in_order_count() < 1">
        Вы еще не выбрали ни одного экрана
        Вы сможете это в специальном разделе, пройдя по ссылке ниже
        или отправить нам заявку в произвольной форме
        <br>
        <a class="pseudo-link" href="{% url 'cities' %}">ВЫБРАТЬ ЭКРАНЫ</a>
    </div>
</div>

{% if groups %}
    <div class="ngdialog-header animate-if" ng-if="$root.has_group()">
        <p class="order-items-title">Выбранные пакеты</p>
    </div>
    <div class="ngdialog-order-list">
        {% for group in groups %}
            <div class="order-item-group item_group animate-if" ng-if="$root.findGroupInOrder({{ group.id }})">
                <a href="javascript:void(0)" ng-click="$root.removeGroup({{ group.id }})"
                   class="pseudo-link">{{ group.name }}</a>
                <a href="javascript:void(0)" ng-click="$root.removeGroup({{ group.id }})" class="trash-link"><i
                        class="fa fa-trash-o"></i></a>
            </div>
        {% endfor %}
    </div>
{% endif %}
{% if leds %}
    <div class="ngdialog-header animate-if" ng-if="$root.leds_not_in_group()">
        <p class="order-items-title">Выбранные экраны</p>
    </div>
    <div class="ngdialog-order-list">
        {% for led in leds %}
            <div class="order-item-group item_led animate-if" ng-if="$root.findLedInOrder({{ led.id }})">
                <a href="javascript:void(0)" ng-click="$root.removeLed({{ led.id }})" class="pseudo-link">{{ led.name }}, {{ led.address }}</a>
                <a href="javascript:void(0)" ng-click="$root.removeLed({{ led.id }})" class="trash-link"><i
                        class="fa fa-trash-o"></i></a>
            </div>
        {% endfor %}
    </div>
{% endif %}

<div ng-show="orderSended" class="thanks-info title">
    Спасибо за заказ, скоро мы свяжемся с вами
</div>

<div class="ngdialog-order-form">
    <div ng-hide="orderSended">
        <p class="title error" ng-show="!orderForm.$valid">Все поля обязательны для заполнения</p>

        <p class="title" ng-show="orderForm.$valid">Можете совершить заказ</p>

        <form name="orderForm">
            <div class="control-group">
                <input name="company" ng-class="{error: orderForm.company.$error.required}" ng-model="customer.company"
                       type="text" class="control" placeholder="Компания" required>
                <input name="person" ng-class="{error: orderForm.person.$error.required}" ng-model="customer.person"
                       type="text" class="control" placeholder="Контактное лицо" required>
            </div>
            <div class="control-group">
                <input name="email" ng-class="{error: orderForm.email.$error.required}" ng-model="customer.email"
                       type="text" class="control" placeholder="Email" required>
                <input name="phone" ng-class="{error: orderForm.phone.$error.required}" ng-model="customer.phone"
                       type="text" class="control" placeholder="Телефон" required>
            </div>
    <textarea name="comment" ng-class="{error: orderForm.comment.$error.required}" ng-model="customer.comment"
              class="control" required
              placeholder="Пожалуйста, укажите в комментарии примерный срок начала и продолжительность рекламной кампании, а также хронометраж ролика — эти данные необходимы для корректного расчета"></textarea>

            <div class="text-center mt-20">
                <a href="javascript:void(0)" ng-click="sendOrder()" class="btn btn--big"
                   ng-class="{'btn--disabled': !orderForm.$valid && $root.in_order_count() > 0}">отправить</a>
            </div>
        </form>
    </div>
</div>