main/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from cities.views import CityView
from leds.views import JsonContent

urlpatterns = [
                  url(r'^admin/', include(admin.site.urls)),

                  url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
                  url(r'^cities$', TemplateView.as_view(template_name='cities.html'), name='cities'),

                  url(r'^cities/(?P<slug>.*)$', CityView.as_view(), name='city'),
                  url(r'^about/', TemplateView.as_view(template_name='about.html'), name='about_led'),
                  url(r'^contacts/', TemplateView.as_view(template_name='contacts.html'), name='contacts'),
                  url(r'^api/', csrf_exempt(JsonContent.as_view()), name='api'),

                  url(r'^redactor/', include('redactor.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cities/models.py
#! coding: UTF-8
from django.db import models
from django.db.models import permalink
from django.template.defaultfilters import slugify
from django_ymap.fields import YmapCoord
from redactor.fields import RedactorField


class City(models.Model):
    name = models.CharField(max_length=255, verbose_name=u'Название')
    slug = models.SlugField(max_length=50, verbose_name=u'URL')
    description = RedactorField(blank=True, verbose_name=u'Описание')
    center = YmapCoord(max_length=200, default=None, blank=True, null=True, start_query=u'Москва', size_width=980,
                       size_height=500, verbose_name=u'Центр')

    @permalink
    def get_absolute_url(self):
        return 'city', self.id

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'Город'
        verbose_name_plural = u'Города'


class MapBall(models.Model):
    name = models.CharField(max_length=255, verbose_name=u'Название зоны')
    size = models.PositiveSmallIntegerField(default=0, verbose_name=u'Размер круга в пикселях',
                                            help_text=u'0 - вычисляется из количества связанных городов')

    cities = models.ManyToManyField(City, verbose_name=u'Связанные города')
    pos_x = models.PositiveSmallIntegerField(default=0, verbose_name=u'Позиция по горизонтали')
    pos_y = models.PositiveSmallIntegerField(default=0, verbose_name=u'Позиция по вертикали')

    def get_size(self):
        return self.size

    class Meta:
        verbose_name = u'Метку'
        verbose_name_plural = u'Метки на карте России'

    def __unicode__(self):
        return self.name

leds/models.py
#! coding: UTF-8
from django.db import models
from django_ymap.fields import YmapCoord
from redactor.fields import RedactorField


class Led(models.Model):
    name = models.CharField(max_length=255, verbose_name=u'Название')
    city = models.ForeignKey('cities.City', verbose_name=u'Город')
    address = models.CharField(max_length=255, verbose_name=u'Адрес')
    text = RedactorField(blank=True, verbose_name=u'Описание')

    center = YmapCoord(max_length=200, default=None, blank=True, null=True, start_query=u'Москва', size_width=980,
                       size_height=500, verbose_name=u'Центр')


    class Meta:
        verbose_name = u'Экран'
        verbose_name_plural = u'Экраны'

    def __unicode__(self):
        return self.name

class LedImage(models.Model):
    led = models.ForeignKey('Led')
    image = models.ImageField(upload_to='uploads', verbose_name=u'Фотография')

    class Meta:
        verbose_name = u'Фотография экрана'
        verbose_name_plural = u'Фотографии'

    def __unicode__(self):
        return u''


class LedGroup(models.Model):
    name = models.CharField(max_length=255, verbose_name=u'Название')
    leds = models.ManyToManyField('Led', verbose_name=u'Связанные экраны')
    city = models.ForeignKey('cities.City', verbose_name=u'Город')

    def led_array(self):
        return list(self.leds.values_list('id', flat=True))

    class Meta:
        verbose_name = u'Пакет'
        verbose_name_plural = u'Пакеты экранов'

    def __unicode__(self):
        return self.name

main/models.py
#! coding: UTF-8
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import permalink
from django_ymap.fields import YmapCoord
from redactor.fields import RedactorField


class Order(models.Model):
    company = models.CharField(max_length=255, verbose_name=u'Компания')
    person = models.CharField(max_length=255, verbose_name=u'Контактное лицо')
    email = models.EmailField(max_length=255, verbose_name=u'Email')
    phone = models.CharField(max_length=255, verbose_name=u'Телефон')
    comment = models.TextField()

    leds = models.ManyToManyField('leds.Led', verbose_name=u'Экраны в заказе')
    groups = models.ManyToManyField('leds.LedGroup', verbose_name=u'Пакеты в заказе')

    success = models.BooleanField(default=False, verbose_name=u'Выполнен')

    class Meta:
        verbose_name = u'Заказ'
        verbose_name_plural = u'Заказы'

    def get_admin_link(self):
        return reverse('admin:main_order_change', args=(self.id,))

    def __unicode__(self):
        return '%s, %s' %(self.pk, self.person)


class Question(models.Model):
    name = models.CharField(max_length=255, verbose_name=u'Имя')
    phone = models.CharField(max_length=255, verbose_name=u'Телефон')
    email = models.EmailField(max_length=255, verbose_name=u'Email')
    issue = models.TextField(verbose_name=u'Вопрос')
    success = models.BooleanField(default=False, verbose_name=u'Решен')

    class Meta:
        verbose_name = u'Вопрос'
        verbose_name_plural = u'Вопросы'

    def __unicode__(self):
        return '%s, %s' %(self.name, self.issue)

    def get_admin_link(self):
        return reverse('admin:main_question_change', args=(self.id,))


class FastBid(models.Model):
    text = models.TextField(verbose_name=u'Быстрая заявка')
    success = models.BooleanField(default=False, verbose_name=u'Обработана')

    class Meta:
        verbose_name = u'Быструю заявку'
        verbose_name_plural = u'Быстрые заявки'

    def __unicode__(self):
        return self.text

    def get_admin_link(self):
        return reverse('admin:main_fastbid_change', args=(self.id,))

class LedoutdoorSettings(models.Model):
    index = RedactorField(verbose_name=u'Соержимое главной страницы', blank=True)
    about_led = RedactorField(verbose_name=u'Содержимое страницы "О LED экранах"', blank=True)
    contacts = RedactorField(verbose_name=u'Содержимое страницы "Контакты"', help_text=u'Содержание верхнего блока на странице "Контакты"', blank=True)
    phone_n = models.CharField(max_length=255, verbose_name=u'Телефон', help_text=u'Отображается в верхнем углу сайта на главной странице', blank=True)
    email_n = models.CharField(max_length=255, verbose_name=u'Почта', help_text=u'Отображается в верхнем углу сайта на главной странице', blank=True)
    email_for_notice = models.CharField(max_length=255, verbose_name=u'Почта для связи', help_text=u'На эту почту будут отсылаться уведомление о заказах', blank=True)
    address_coord = YmapCoord(max_length=200, default=None, blank=True, null=True, start_query=u'Москва', size_width=980,
                       size_height=500, verbose_name=u'Адрес офиса')

    title_index = models.CharField(max_length=255, verbose_name=u'Заголовок главной страницы', blank=True)
    description_index = models.CharField(max_length=255, verbose_name=u'Описание главной страницы', blank=True)
    keywords_index = models.CharField(max_length=255, verbose_name=u'Ключевые слова главной страницы', blank=True)

    title_cities = models.CharField(max_length=255, verbose_name=u'Заголовок страницы каталога', blank=True)
    description_cities = models.CharField(max_length=255, verbose_name=u'Описание страницы каталога', blank=True)
    keywords_cities = models.CharField(max_length=255, verbose_name=u'Ключевые слова страницы каталога', blank=True)

    title_about_led = models.CharField(max_length=255, verbose_name=u'Заголовок страницы о LED экранах', blank=True)
    description_about_led = models.CharField(max_length=255, verbose_name=u'Описание страницы о LED экранах', blank=True)
    keywords_about_led = models.CharField(max_length=255, verbose_name=u'Ключевые слова страницы о LED экранах', blank=True)

    title_city = models.CharField(max_length=255, verbose_name=u'Заголовок страницы города', blank=True, help_text=u'''
    Эти поля принимают шаблон, доступные переменные {{slug}}, {{description}}, {{name}}, {{center}}''')
    description_city = models.CharField(max_length=255, verbose_name=u'Описание страницы города', blank=True)
    keywords_city = models.CharField(max_length=255, verbose_name=u'Ключевые слова страницы города', blank=True)

    title_contact = models.CharField(max_length=255, verbose_name=u'Заголовок страницы контактов', blank=True)
    description_contact = models.CharField(max_length=255, verbose_name=u'Описание страницы контактов', blank=True)
    keywords_contact = models.CharField(max_length=255, verbose_name=u'Ключевые слова страницы контактов', blank=True)

    footer = RedactorField(verbose_name=u'Подвал', help_text=u'Отображается оостветственно в подвале сайта')
    snippets = models.TextField(blank=True, verbose_name=u'Код', help_text=u'JS код для счетчиков и прочего, вставляется в конец сайта')

    advantages_1 = models.TextField(blank=True)
    advantages_2 = models.TextField(blank=True)
    advantages_3 = models.TextField(blank=True)

    class Meta:
        verbose_name = u'Настройки сайта'
        verbose_name_plural = u'Настройки сайта'

    def __unicode__(self):
        return u'Настройки'

cities/views.py
import json
from django.template import Context, Template
from django.views.generic import DetailView
from cities.models import City
from main.models import LedoutdoorSettings


class CityView(DetailView):
    model = City
    template_name = 'city.html'
    context_object_name = 'city'

    def get_context_data(self, **kwargs):
        context = super(CityView, self).get_context_data(**kwargs)
        settings = LedoutdoorSettings.objects.all()[0]

        from django.core import serializers
        data = json.loads(serializers.serialize("json", [self.object]))

        context['city_title'] = Template(settings.title_city).render(Context(data[0]['fields']))
        context['city_description'] = Template(settings.description_city).render(Context(data[0]['fields']))
        context['city_keywords'] = Template(settings.keywords_city).render(Context(data[0]['fields']))
        print(context)
        return context

main/templates/about.html
{% extends 'base.html' %}
{% block header %}{% endblock %}
{% block about_led %}active{% endblock %}
{% block nav_class %} wide{% endblock %}
{% block content %}
    <div class="container content about_led">
        <div class="prefix-1 column-22 suffix-1">
            {{ about_led_content|safe }}
        </div>
        <div class="prefix-3 column-18 suffix-3 mt-40">
            <hr>
        </div>
        <div class="clear"></div>
    </div>
{% endblock %}

main/templates/base.html
{% load staticfiles i18n leds_tags %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="Keywords" content="{% block keywords %}{% endblock %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=latin,cyrillic'
          rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'js/components/ng-dialog/css/ngDialog.min.css' %}">

    <script src="{% static 'js/components/angular/angular.min.js' %}"></script>
    <script src="{% static 'js/components/angular-animate/angular-animate.min.js' %}"></script>
    <script src="{% static 'js/components/angular-filter/dist/angular-filter.min.js' %}"></script>
    <script src="{% static 'js/components/ng-dialog/js/ngDialog.min.js' %}"></script>
    <script src="{% static 'js/ya-map-2.1.min.js' %}"></script>
    <script src="{% static 'js/components/underscore/underscore-min.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>

    <title>Ledoutdoor</title>
</head>
<body ng-app="App">
{% block header %}
    <header>
        <div class="credits">
            <span><i class="fa fa-phone"></i>{{ phone_number }}</span><br>
            <a href="mailto:{{ email }}"><i class="fa fa-envelope"></i>{{ email }}</a>
        </div>
        <div class="billboard">
            <div class="billboard__outer"></div>
            <div class="billboard__inner">
                <video loop autoplay>
                    <source src="{% static 'img/abstract.mp4' %}">
                    <source src="{% static 'img/abstract.webm' %}">
                </video>
                <div class="billboard__content">
                    <a href="{% url 'cities' %}" class="left">Карта видеоэкранов</a>
                    <a href="javascript:void(0)" ng-click="$root.openFastbid()" class="right">Быстрая заявка</a>
                </div>
            </div>
        </div>
    </header>
{% endblock %}
<nav class="container{% block nav_class %}{% endblock %}">
    <ul>
        <li class="{% block about %}{% endblock %}"><a href="{% url 'home' %}">О компании</a></li>
        <li class="{% block cities %}{% endblock %}"><a href="{% url 'cities' %}">Каталог</a></li>
        <li class="{% block about_led %}{% endblock %}"><a href="{% url 'about_led' %}">О LED дисплеях</a></li>
        <li class="{% block contacts %}{% endblock %}"><a href="{% url 'contacts' %}">Контакты</a></li>
        <li><a class="order" href="javascript:void(0)" ng-click="$root.openOrder()">Сделать заказ (<span ng-bind="$root.in_order_count()">0</span>)</a></li>
    </ul>
</nav>
{% block content %}{% endblock %}
<footer class="container">
    <p>{{ footer_content|safe }}</p>
</footer>
{% include 'svg-store.html' %}
{% get_packages %}
{{ snippets|safe }}
</body>
</html>

main/templates/cities.html
{% extends 'base.html' %}
{% load cities_tags %}
{% block header %}{% endblock %}
{% block cities %}active{% endblock %}
{% block nav_class %} wide{% endblock %}
{% block title %}{{ cities_title }}{% endblock %}
{% block description %}{{ cities_description }}{% endblock %}
{% block keywords %}{{ cities_keywords }}{% endblock %}
{% block content %}
    <div ng-controller="citiesController">
        <div class="map-container">
            <div class="map" ng-class="{show: true}">
                <div class="map__ball" ng-repeat="ball in balls"
                     ng-style="{top: ball.pos_y +'px', left: ball.pos_x +'px', width: ball.size+'px', height: ball.size+'px'}"
                     ng-show="ball.pos_y <= showRect[1] && ball.pos_x <= showRect[0]">
                    <div class="map__ball__popup"
                         ng-style="{bottom: ball.size + 'px', 'margin-left': -125 + ball.size / 2 + 'px'}">
                        <div class="header">
                            <span class="left">Город</span>
                            <span class="right">Экранов</span>
                        </div>
                        <a ng-href="/cities/{$ city.slug $}" ng-repeat="city in ball.cities">
                            <span class="left">{$ city.name $}</span>
                            <span class="right">{$ city.count $}</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="container content cities" ng-controller="citiesController">
            <div class="prefix-1 column-22 suffix-1">
                <input type="text" class="control" placeholder="Найти город" size="60" ng-model="search_string">
            </div>
            <div class="prefix-1 column-22 suffix-1 cities__list">
                <div class="cities__list__letter-block" ng-repeat="(letter, list) in cities | groupBy: 'letter'">
                    <span class="letter" ng-hide="search_string && !contains(list, search_string)">{$ letter $}</span>
                    <a ng-href="/cities/{$ city.slug $}" ng-repeat="city in list | filter: search_string">{$ city.name $}</a>
                </div>
            </div>
            <div class="prefix-3 column-18 suffix-3">
                <hr>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    {% get_cities_json %}
    {% get_balls_json %}
{% endblock %}

main/templates/city.html
{% extends 'base.html' %}
{% load splitter leds_tags %}
{% block cities %}active{% endblock %}
{% block header %}{% endblock %}
{% block nav_class %} wide{% endblock %}
{% block title %}{{ city_title }}{% endblock %}
{% block description %}{{ city_description }}{% endblock %}
{% block keywords %}{{ city_keywords }}{% endblock %}
{% block content %}
    <div class="container content city" ng-controller="cityController">
        <div class="prefix-1 column-22 suffix-1">

            <div class="breadcrumbs">
                <a href="{% url 'cities' %}">Карта</a>
                <span>&nbsp;&ndash;&nbsp;</span>
                <a class="active">{{ city.name }}</a>
            </div>
        </div>
        <div class="column-24 city__title">
            <h1 class="text-center">{{ city.name }}</h1>
        </div>
        <div class="push-1 column-22 city__balloon">
            <div class="column-8 info">
                <span class="info__text">Экранов в городе:&nbsp;</span>
                <span class="info__num">{{ city.led_set.count }}</span>

                {% comment %}
                <div class="info__big">
                    <span class="info__text">Выбрано:&nbsp;</span>
                    <span class="info__num"></span>
                </div>
                {% endcomment %}
            </div>
            <div class="column-14 packages">
                {% if city.ledgroup_set.count > 0 %}
                    <p class="packages__title">Пакеты</p>

                    <div class="packages__list">
                        {% for package in city.ledgroup_set.all %}
                            <div class="control-group" tooltip="{{ package.short_info }}">
                                <input type="checkbox" ng-model="$root.ledsGroup[{{ package.id }}]"
                                       ng-true-value="{{ package.led_array }}" class="control"
                                       id="group_{{ forloop.counter }}">
                                <label for="group_{{ forloop.counter }}" class="css-label">{{ package.name }}</label>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <p class="packages__title"></p>
                {% endif %}
            </div>
            {% if city.description %}
                <div class="column-24 city__description">
                    {{ city.description|safe }}
                </div>
            {% endif %}

        </div>
        <div class="column-24 text-center">
            <p class="view-checker--title">Отображать</p>

            <div class="view-checker">
                <a ng-click="showMap = false" ng-class="{'btn--disabled': showMap}" class="btn">Списком</a>
                <a ng-click="showMap = true" ng-class="{'btn--disabled': !showMap}" class="btn">На карте</a>
            </div>
        </div>
        <div class="column-24 leds">
            <div class="leds__list" ng-show="!showMap">
                {% for led_column in city.led_set.all|splitter:2 %}
                    <div class="leds__list--column">
                        {% for led in led_column %}
                            {% if led %}
                                <div class="control-group">
                                    <input type="checkbox" ng-model="$root.leds[{{ led.id }}]" class="control"
                                           id="led_{{ led.id }}" style="display: block">
                                    <label for="led_{{ led.id }}" class="css-label"></label>
                                    <a href="javascript:void(0)" ng-click="openDetail('{{ led.id }}')"
                                       class="pseudo-link">{{ led.name }}, {{ led.address }}</a>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
            <div class="leds__on-map" ng-show="showMap">
                <div ng-hide="mapLoaded" class="md-preloader">
                    <svg xmlns="http://www.w3.org/2000/svg" version="1.1" height="50" width="50" viewbox="0 0 75 75">
                        <circle cx="37.5" cy="37.5" r="33.5" stroke-width="4"/>
                    </svg>
                </div>
                <ya-template-layout ya-key="balloon" ya-overrides="overrides">
                    <div class="control-group">
                        <input data-id="$[properties.id]" data-name="$[properties.name]" id="mapLedCheckbox"
                               class="control" type="checkbox"/>
                        <label for="mapLedCheckbox"
                               class="css-label"></label>
                        <a href="javascript:void(0)" class="pseudo-link" id="mapInfoLink" data-id="$[properties.id]">$[properties.name],
                            $[properties.address]</a>
                    </div>
                </ya-template-layout>
                <ya-map ng-if="showMap" ya-zoom="12" ya-after-init="afterMapInit($target); updateProxy();"
                        ya-center='{$ center $}' ya-before-init="centerOnCity('{{ city.name }}', '{{ city.center }}')">
                    {% for led in city.led_set.all %}
                        <ya-geo-object id="geo_{{ led.id }}"
                                       ya-event-mouseenter="openBalloon($event)"
                                       ya-source="{geometry: {type: 'Point', coordinates: '{{ led.center }}'.split(',').reverse()}, properties: {name: '{{ led.name }}', id:{{ led.id }}, address:'{{ led.address }}'}}"
                                       ya-options="{led_id:{{ led.id }}, balloonContentLayout:'balloon',balloonPanelMaxMapArea: 0, balloonCloseButton: true, preset: 'islands#circleDotIcon', iconColor: '#0496b0',hideIconOnBalloonOpen: false}"></ya-geo-object>
                    {% endfor %}
                </ya-map>
            </div>
        </div>
        <div class="prefix-3 column-18 suffix-3">
            <hr>
        </div>
        <div class="clear"></div>
    </div>
{% endblock %}

main/templates/contacts.html
{% extends 'base.html' %}
{% block header %}{% endblock %}
{% block contacts %}active{% endblock %}
{% block nav_class %} wide{% endblock %}
{% block title %}{{ contacts_title }}{% endblock %}
{% block description %}{{ contacts_description }}{% endblock %}
{% block keywords %}{{ contacts_keywords }}{% endblock %}
{% block content %}
    <div class="container content contacts" ng-controller="contactsController">
        <div class="prefix-1 column-11 contact-map">
            <ya-map ya-zoom="12" style="width: 100%; height: 400px; display: block;"
                    ya-center="'{{ address_coord }}'.split(',').reverse()">
                <ya-geo-object
                        ya-source="{geometry: {type: 'Point', coordinates: '{{ address_coord }}'.split(',').reverse() }
                        , properties: {iconContent: 'Led-Outdoor'}}"
                        ya-options="{preset: 'islands#blueStretchyIcon'}"></ya-geo-object>
            </ya-map>
        </div>
        <div class="column-11 suffix-1">
            <p class="column-24 sub-title">Наши контакты:</p>

            <div class="column-24">{{ contacts_content|safe }}</div>
            <div ng-show="issueSended">
                <p class="column-24 sub-title thanks-info">Спасибо за вопрос, скоро мы свяжемся с вами</p>
            </div>
            <div ng-show="!issueSended">

                <p class="column-24 sub-title">Задать вопрос:</p>

                <form name="issueForm">
                    <div class="control-group--block">
                        <label for="name" class="column-6">Ваше имя:</label>
                        <input ng-model="customer.name" name="name" type="text"
                               ng-class="{error: issueForm.name.$error.required}"
                               class="control column-17 mb-20" required>
                    </div>
                    <div class="control-group--block" ng-show="!customer.phone && !customer.email">
                        <div class="column-6">&nbsp;</div>
                        <div class="column-17 error">Cообщите как с вами связаться</div>
                    </div>
                    <div class="control-group--block">
                        <label for="name" class="column-6">Телефон:</label>
                        <input ng-class="{error: !customer.phone && !customer.email}" ng-model="customer.phone"
                               name="phone"
                               type="text" class="control column-17 mb-20">
                    </div>
                    <div class="control-group--block">
                        <label for="name" class="column-6">Email:</label>
                        <input ng-class="{error: !customer.phone && !customer.email}" ng-model="customer.email"
                               name="email"
                               type="text" class="control column-17 mb-20">
                    </div>
                    <div class="control-group--block">
                        <label for="name" class="column-6">Вопрос:</label>
                <textarea ng-model="customer.issue" name="issue" type="text"
                          ng-class="{error: issueForm.issue.$error.required}" class=" control column-17"
                          required></textarea>
                        <a href="javascript:void(0)" class="btn btn--big" ng-click="sendIssue()"
                           ng-class="{'btn--disabled': !customer.phone && !customer.email || !issueForm.$valid}">Отправить</a>
                    </div>
                </form>
            </div>

        </div>
        <div class="prefix-3 column-18 suffix-3 mt-40">
            <hr>
        </div>
        <div class="clear"></div>
    </div>
{% endblock %}

main/templates/index.html
{% extends 'base.html' %}
{% block about %}active{% endblock %}
{% block title %}{{ index_title }}{% endblock %}
{% block description %}{{ index_description }}{% endblock %}
{% block keywords %}{{ index_keywords }}{% endblock %}
{% block content %}
    <div class="container content">
        <div class="prefix-1 column-22 suffix-1 pb-40">
            {{ index_content|safe }}
        </div>
        <div class="alpha column-24 advantages omega">
            <div class="advantages__inner container-fluid">
                <div class="column-24 advantages__title">Наши приемущества</div>
                <div class="column-8 advantages__item">
                    <svg height="80" width="80" style="fill: white">
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#film"></use>
                    </svg>
                    <p>{{ advantages_1 }}</p>
                </div>
                <div class="column-8 advantages__item">
                    <svg height="80" width="80" style="fill: white">
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#picture"></use>
                    </svg>
                    <p>{{ advantages_2 }}</p>
                </div>
                <div class="column-8 advantages__item">
                    <svg height="80" width="80" style="fill: white">
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#sun"></use>
                    </svg>
                    <p>{{ advantages_3 }}</p>
                </div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
{% endblock %}

main/templates/svg-store.html
<div style="display: none">
    <svg xmlns="http://www.w3.org/2000/svg"><symbol viewBox="0 0 18.24 18.24" id="film"><title>film</title> <path d="M0,0v18.24h1.611v-1.632H3.27v1.632h11.607v-1.632h1.658v1.632h1.705V0H0z M3.27,14.924H1.611v-1.658
	H3.27V14.924z M3.27,11.607H1.611V9.949H3.27V11.607z M3.27,8.291H1.611V6.633H3.27V8.291z M3.27,4.975H1.611V3.316H3.27V4.975z
	 M3.27,1.684H1.611V0.026H3.27V1.684z M13.244,16.582H4.928V9.949h8.316V16.582z M13.244,8.291H4.928V1.658h8.316V8.291z
	 M16.535,14.924h-1.658v-1.658h1.658V14.924z M16.535,11.607h-1.658V9.949h1.658V11.607z M16.535,8.291h-1.658V6.633h1.658V8.291z
	 M16.535,4.975h-1.658V3.316h1.658V4.975z M16.535,1.684h-1.658V0.026h1.658V1.684z"></path> </symbol><symbol viewBox="0 0 25.68 18.72" id="picture"><title>picture</title> <path d="M8.264,5.37c0,0.992-0.805,1.801-1.799,1.801c-0.989,0-1.796-0.809-1.796-1.801
	c0-0.997,0.807-1.801,1.796-1.801C7.459,3.569,8.264,4.374,8.264,5.37z"></path> <path d="M3.629,13.985c0,0,3.098-6.49,5.506-6.49c2.405,0,3.705,2.829,3.705,2.829s2.521-5.699,4.624-5.699
	s4.587,9.36,4.587,9.36H3.629z"></path> <path d="M23.345,2.34v14.04H2.334V2.34H23.345 M23.345,0H2.334C1.046,0,0,1.047,0,2.34v14.04
	c0,1.293,1.046,2.34,2.334,2.34h21.011c1.291,0,2.334-1.047,2.334-2.34V2.34C25.68,1.047,24.636,0,23.345,0L23.345,0z"></path> </symbol><symbol viewBox="0 0 19.44 19.44" id="sun"><title>sun</title> <path d="M14.036,9.711c0,2.427-1.967,4.393-4.394,4.393c-2.425,0-4.393-1.966-4.393-4.393
	s1.968-4.394,4.393-4.394C12.069,5.318,14.036,7.285,14.036,9.711z"></path> <path d="M10.597,3.612H8.84v-3.59h1.757V3.612z"></path> <path d="M10.597,19.417H8.84v-3.59h1.757V19.417z"></path> <path d="M15.828,10.597V8.839h3.59v1.757H15.828z"></path> <path d="M0.022,10.597V8.839h3.59v1.757H0.022z"></path> <path d="M5.68,3.983l-1.738,1.74L1.457,3.238l1.738-1.74L5.68,3.983z"></path> <path d="M17.917,16.222l-1.74,1.737l-2.485-2.485l1.74-1.74L17.917,16.222z"></path> <path d="M15.464,5.723l-1.74-1.74l2.485-2.485l1.74,1.74L15.464,5.723z"></path> <path d="M3.228,17.959l-1.74-1.74l2.485-2.485l1.74,1.74L3.228,17.959z"></path> </symbol></svg>
</div>